spring.config.import=optional:file:.env[.properties]

spring.application.name=plant-identifier

#Database credentials
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JWT secret key
security.jwt.secret-key =${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000

#Database settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.logging.level.com.example.plant-identifier=DEBUG

server.port=8080

# Application URL configuration
# For local development
app.base-url=http://localhost

# For production, change to your domain
# app.base-url=https://yourdomain.com